import requests
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt
from unicodedata import normalize
import pandas as pd
import os.path

from golgg.pipeline.common import log_step_end, log_step_start

headers = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) '\
           'AppleWebKit/537.36 (KHTML, like Gecko) '\
           'Chrome/75.0.3770.80 Safari/537.36'}
start_time = log_step_start("step008x_timeline_kills_partidas_torneio")
df = pd.read_csv('golgg/torneios/CBLOL Cup 2026/CBLOL_Cup_2026.csv')
info_teams = pd.read_csv('golgg/source/info_teams.csv')

# Support current CSV headers generated by Step 1/Step 2.
df = df.rename(columns={'Partida': 'partida'})
info_teams = info_teams.rename(columns={'Player': 'player', 'Role': 'role', 'Team': 'nome_time'})


def to_timeline_url(match_link):
  url = str(match_link).strip()
  if 'page-summary/' in url:
    return url.replace('page-summary/', 'page-timeline/')
  if url.endswith('/'):
    return url + 'page-timeline/'
  return url + '/page-timeline/'


soloers = []
for index, partida in df.iterrows():
  # print(partida['partida'])
  url = to_timeline_url(partida['Link'])
  httpx = requests.get(url, headers=headers)
  string = httpx.text
  soup = BeautifulSoup(string, 'html.parser')
  table = soup.find_all("table", attrs={'class':'nostyle timeline trhover'})
  if len(table) == 0:
      continue
  rows = table[0].find_all("tr", recursive=False)
  li = rows[1:]
  for x in li:
      solo = {}
      chi = x.find_all("td", recursive=False)
      if len(chi[3]) == 1 and chi[4].find(attrs={'src':'../_img/kill-icon.png'}):
          # print (chi[2].text,"solo'd",chi[6].text)
          solo['torneio'] = soup.find("div", attrs={"class":"col-12 mt-4"}).findChild("a").text
          solo['player'] = chi[2].text
          if chi[2].text == '':
            solo['role'] = ''
            solo['team'] = ''
          else:
            solo['role'] = info_teams[info_teams['player'] == chi[2].text]['role'].values[0]
            solo['team'] = info_teams[info_teams['player'] == chi[2].text]['nome_time'].values[0]
          solo['partida'] = partida['partida']
          try:
            solo['teamWinner'] = soup.find(string=" - WIN").find_previous_sibling().text
          except:
            solo['teamWinner'] = soup.find(string=" - WIN ").find_previous_sibling().text
          solo['target'] = chi[6].text
          solo['target_role'] = info_teams[info_teams['player'] == chi[6].text]['role'].values[0]
          soloers.append(solo)

solo_kills = pd.DataFrame(soloers)

solo_kills = pd.DataFrame(solo_kills[['torneio', 'player', 'role', 'team', 'partida', 'teamWinner', 'target', 'target_role']].value_counts().to_frame('count'))
solo_kills
solo_kills.to_csv("golgg/source/all_solokills.csv")
solo_kills = pd.read_csv("golgg/source/all_solokills.csv")
solo_kills

killers = []
for index, partida in df.iterrows():
  # print(partida['partida'])
  url = to_timeline_url(partida['Link'])
  httpx = requests.get(url, headers=headers)
  string = httpx.text
  soup = BeautifulSoup(string, 'html.parser')
  table = soup.find_all("table", attrs={'class':'nostyle timeline trhover'})
  if len(table) == 0:
      continue
  rows = table[0].find_all("tr", recursive=False)
  li = rows[1:]
  for x in li:
      kill = {}
      chi = x.find_all("td", recursive=False)
      if len(chi[3]) >= 1 and chi[4].find(attrs={'src':'../_img/kill-icon.png'}):
          # print (chi[2].text,"kill'd",chi[6].text)
          kill['torneio'] = soup.find("div", attrs={"class":"col-12 mt-4"}).findChild("a").text
          kill['player'] = chi[2].text
          if chi[2].text == '':
            kill['role'] = ''
            kill['team'] = ''
          else:
            kill['role'] = info_teams[info_teams['player'] == chi[2].text]['role'].values[0]
            kill['team'] = info_teams[info_teams['player'] == chi[2].text]['nome_time'].values[0]
          kill['partida'] = partida['partida']
          try:
            kill['teamWinner'] = soup.find(string=" - WIN").find_previous_sibling().text
          except:
            kill['teamWinner'] = soup.find(string=" - WIN ").find_previous_sibling().text          
          kill['target'] = chi[6].text
          kill['target_role'] = info_teams[info_teams['player'] == chi[6].text]['role'].values[0]
          killers.append(kill)

all_kills = pd.DataFrame(killers)

all_kills = pd.DataFrame(all_kills[['torneio', 'player', 'role', 'team', 'partida', 'teamWinner', 'target', 'target_role']].value_counts().to_frame('count'))
all_kills
all_kills.to_csv("golgg/source/all_kills.csv")
all_kills = pd.read_csv("golgg/source/all_kills.csv")
all_kills

lista_killers = all_kills['player'].unique()

sum_killers = []
for killer in lista_killers:
  if str(killer) != 'nan':
    sum_killer = {}
    sum_killer['player'] = killer
    sum_killer['role'] = all_kills[all_kills['player'] == killer]['role'].values[0]
    sum_killer['team'] = all_kills[all_kills['player'] == killer]['team'].values[0]
    sum_killer['kills'] = all_kills[all_kills['player'] == killer]['count'].sum()
    target_counts = all_kills[all_kills['player'] == killer].groupby(['target'])['count'].sum().sort_values(ascending=False)
    top_target = target_counts.index[0]
    top_target_count = target_counts.iloc[0]
    sum_killer['fregues'] = str(top_target) + ' x' + str(top_target_count)
    sum_killer['freguesrole'] = all_kills[all_kills['target'] == top_target]['target_role'].values[0]
    sum_killer['solokills'] = solo_kills[solo_kills['player'] == killer]['count'].sum()
    try:
      solo_target_counts = solo_kills[solo_kills['player'] == killer].groupby(['target'])['count'].sum().sort_values(ascending=False)
      top_solo_target = solo_target_counts.index[0]
      top_solo_target_count = solo_target_counts.iloc[0]
      sum_killer['solofregues'] = str(top_solo_target) + ' x' + str(top_solo_target_count)
      sum_killer['solofreguesrole'] = solo_kills[solo_kills['target'] == top_solo_target]['target_role'].values[0]
    except:
      sum_killer['solofregues'] = '-'
      sum_killer['solofreguesrole'] = '-'
    sum_killer['deaths'] = all_kills[all_kills['target'] == killer]['count'].sum()
    sum_killer['solodeaths'] = solo_kills[solo_kills['target'] == killer]['count'].sum()
    sum_killers.append(sum_killer)

sum_kills = pd.DataFrame(sum_killers)
sum_kills.to_csv("golgg/source/sum_kills.csv", index=False)
sum_kills

roles = ['TOP', 'BOT', 'MID', 'SUPPORT', 'JUNGLE']
sum_kills = pd.read_csv("golgg/source/sum_kills.csv")

for role in roles:
  s = pd.DataFrame(sum_kills[sum_kills['role']==f'{role}'].sort_values("kills", ascending=False)[0:5])
  s.to_csv(f"golgg/source/{role}.csv", index=False)
  s = pd.read_csv(f"golgg/source/{role}.csv")
  for linha in s['player']:
    s.loc[s['player'] == linha,'targeted'] = solo_kills[solo_kills['target'] == linha]['count'].sum().astype(int)
    # print(solo_kills[solo_kills['target'] == linha]['count'].sum().astype(int))
  s.to_csv(f"golgg/source/{role}.csv", index=False)

log_step_end("step008x_timeline_kills_partidas_torneio", start_time)
